openapi: 3.0.0
info:
  title: 늬웃 (article)
  version: 1.0.0
  description: 기사(아티클) 관련 엔드포인트 스펙
servers:
  - url: http://localhost:8080
tags:
  - name: Article
    description: 아티클 관련 API

paths:
  /api/articles:
    get:
      tags: [Article]
      summary: "아티클 목록 조회"
      description: "페이지네이션을 포함한 아티클 목록을 조회합니다"
      parameters:
        - name: page
          in: query
          description: "페이지 번호 (기본값: 1)"
          schema: { type: integer, default: 1 }
        - name: limit
          in: query
          description: "페이지당 아이템 수 (기본값: 20)"
          schema: { type: integer, default: 20 }
      responses:
        '200':
          description: "성공"
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: { type: boolean, example: true }
                  data:
                    type: object
                    properties:
                      articles:
                        type: array
                        items: { $ref: '#/components/schemas/ArticleListItem' }
                      pagination: { $ref: '#/components/schemas/Pagination' }
        '500':
          description: "서버 오류"
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ErrorResponse' }

  /api/articles/{id}:
    get:
      tags: [Article]
      summary: "아티클 상세 조회"
      description: "특정 아티클의 상세 정보를 조회합니다"
      parameters:
        - name: id
          in: path
          required: true
          description: "아티클 ID"
          schema: { type: integer, example: 1 }
      responses:
        '200':
          description: "성공"
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: { type: boolean, example: true }
                  data:
                    type: object
                    properties:
                      article:
                        type: array
                        items: { $ref: '#/components/schemas/ArticleDetail' }
                      userInteractions: { $ref: '#/components/schemas/UserInteractions' }
        '404':
          description: "아티클을 찾을 수 없음"
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ErrorResponse' }
        '500':
          description: "서버 오류"

  /api/articles/{id}/bookmark:
    post:
      tags: [Article]
      summary: "북마크 토글"
      description: "아티클 북마크를 등록하거나 해제합니다"
      security: [{ bearerAuth: [] }]
      parameters:
        - name: id
          in: path
          required: true
          description: "아티클 ID"
          schema: { type: integer, example: 1 }
      responses:
        '200':
          description: "성공"
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: { type: boolean, example: true }
                  message: { type: string, example: "북마크에 추가되었습니다" }
                  bookmarked: { type: boolean, example: true }
        '401':
          description: "인증 필요"
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ErrorResponse' }
        '404':
          description: "아티클을 찾을 수 없음"

  /api/articles/{id}/like:
    post:
      tags: [Article]
      summary: "좋아요 토글"
      description: "아티클 좋아요를 등록하거나 취소합니다"
      security: [{ bearerAuth: [] }]
      parameters:
        - name: id
          in: path
          required: true
          description: "아티클 ID"
          schema: { type: integer, example: 1 }
      responses:
        '200':
          description: "성공"
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: { type: boolean, example: true }
                  message: { type: string, example: "좋아요가 등록되었습니다" }
                  liked: { type: boolean, example: true }
        '401':
          description: "인증 필요"
        '404':
          description: "아티클을 찾을 수 없음"

  /api/articles/{id}/rating:
    post:
      tags: [Article]
      summary: "별점 등록"
      description: "아티클에 별점을 등록합니다 (1회만 가능)"
      security: [{ bearerAuth: [] }]
      parameters:
        - name: id
          in: path
          required: true
          description: "아티클 ID"
          schema: { type: integer, example: 1 }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                rating: { type: integer, minimum: 1, maximum: 5, example: 4 }
              required: [rating]
      responses:
        '200':
          description: "성공"
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: { type: boolean, example: true }
                  message: { type: string, example: "별점이 등록되었습니다" }
                  data:
                    type: object
                    properties:
                      userRating: { type: integer, example: 4 }
                      avgRating: { type: number, format: float, example: 4.2 }
                      ratingCount: { type: integer, example: 15 }
        '400':
          description: "잘못된 요청 (이미 평가했거나 잘못된 별점)"
        '401':
          description: "인증 필요"
        '404':
          description: "아티클을 찾을 수 없음"

  /api/articles/search:
    get:
      tags: [Article]
      summary: "아티클 검색"
      description: "키워드나 카테고리로 아티클을 검색합니다"
      parameters:
        - name: keyword
          in: query
          description: "검색 키워드"
          schema: { type: string, example: "경제" }
        - name: category
          in: query
          description: "카테고리"
          schema: { type: string, example: "경제" }
        - name: page
          in: query
          schema: { type: integer, default: 1 }
        - name: limit
          in: query
          schema: { type: integer, default: 20 }
      responses:
        '200':
          description: "성공"
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: { type: boolean }
                  data:
                    type: object
                    properties:
                      articles:
                        type: array
                        items: { $ref: '#/components/schemas/ArticleListItem' }
                      pagination: { $ref: '#/components/schemas/Pagination' }
                      searchInfo:
                        type: object
                        properties:
                          keyword: { type: string, nullable: true }
                          category: { type: string, nullable: true }

  /api/articles/bookmarks/my:
    get:
      tags: [Article]
      summary: "내 북마크 목록"
      description: "로그인한 사용자의 북마크 목록을 조회합니다"
      security: [{ bearerAuth: [] }]
      parameters:
        - name: page
          in: query
          schema: { type: integer, default: 1 }
        - name: limit
          in: query
          schema: { type: integer, default: 20 }
      responses:
        '200':
          description: "성공"
        '401':
          description: "인증 필요"

components:
  schemas:
    ArticleListItem:
      type: object
      properties:
        article_no: { type: integer, example: 1 }
        article_title: { type: string, example: "경제 회복세, 전문가들 긍정적 전망" }
        article_summary:
          type: string
          example: "국내 경제가 점진적 회복세를 보이고 있다.\n전문가들은 하반기 성장률을 긍정적으로 전망한다.\n소비심리 개선과 투자 증가가 주요 요인으로 분석된다."
        article_category: { type: string, example: "경제" }
        article_press: { type: string, example: "경제일보" }
        article_reg_at: { type: string, format: date-time, example: "2025-08-06T12:00:00Z" }
        avg_rating: { type: number, format: float, example: 4.2 }
        likes_count: { type: integer, example: 15 }

    ArticleDetail:
      type: object
      properties:
        article_no: { type: integer, example: 1 }
        article_title: { type: string, example: "경제 회복세, 전문가들 긍정적 전망" }
        article_summary:
          type: string
          example: "국내 경제가 점진적 회복세를 보이고 있다.\n전문가들은 하반기 성장률을 긍정적으로 전망한다.\n소비심리 개선과 투자 증가가 주요 요인으로 분석된다."
        article_content:
          type: string
          example: "국내 경제가 코로나19 팬데믹 이후 점진적인 회복세를 보이며..."
        article_category: { type: string, example: "경제" }
        article_press: { type: string, example: "경제일보" }
        article_source: { type: string, example: "https://news.example.com/economy/1" }
        article_reg_at: { type: string, format: date-time }
        article_update_at: { type: string, format: date-time }
        article_like_count: { type: integer, example: 15 }
        article_rating_avg: { type: number, format: float, example: 4.2 }
        article_view_count: { type: integer, example: 1250 }

    UserInteractions:
      type: object
      properties:
        bookmarked: { type: boolean, example: false }
        liked: { type: boolean, example: false }
        rated: { type: boolean, example: false }
        userRating: { type: integer, nullable: true, example: null }

    Pagination:
      type: object
      properties:
        page: { type: integer, example: 1 }
        limit: { type: integer, example: 20 }
        total: { type: integer, example: 150 }
        totalPages: { type: integer, example: 8 }

    ErrorResponse:
      type: object
      properties:
        success: { type: boolean, example: false }
        message: { type: string, example: "오류 메시지" }

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT